### ISSUE TITLE
Use a licence so other people can use your code.

### ISSUE THREAD

**Issue by hgj** [migzai/irc-api#29]
I would like to create an IRC bot based on your code. It would be nice if you could put in a nice (commercally usable) licence for people who want to use your code legally.

**Comment by migzai** [comment]
How is the current Apache 2.0 license not commercially usable for people who want to use the code legally?

**Comment by hgj** [comment]
I cloned your repository months ago, before you uploaded the licence. I missed that when creating the issue. Sorry about that. 
The Apache licence is prefect! Thanks!
